config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/search', to: 'search#index'

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :parks, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  validates_presence_of :latitude, :longitude, :full_name, :url

  def self.create_parks(park)
    create do |new_park|
      new_park.state            = park[:states]
      new_park.description      = park[:description]
      new_park.directions_info  = park[:directionsInfo]
      new_park.directions_url   = park[:directionsUrl]
      new_park.full_name        = park[:fullName]
      new_park.url              = park[:url]
      new_park.weather_info     = park[:weatherInfo]
      new_park.latitude         = park[:latLong].split(",")[0][4..-1]
      new_park.longitude        = park[:latLong].split(",")[1][6..-1]
    end
  end
end

app/models/photo.rb
class Photo
  attr_reader :title, :url
  def initialize(raw_photo)
    @title      = raw_photo[:title]
    @url        = raw_photo[:url_s]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :uid, :email, :oauth_token

  def self.from_omniauth(auth_info)
    if find_by(uid: auth_info[:uid])
      find_by(uid: auth_info[:uid]).update(oauth_token: auth_info[:credentials][:token])
    else
      create do |new_user|
        new_user.uid                = auth_info['uid']
        new_user.first_name         = auth_info['info']['first_name']
        new_user.name               = auth_info['info']['name']
        new_user.email              = auth_info['info']['email']
        new_user.oauth_token        = auth_info['credentials']['token']
      end
    end
    find_by(uid: auth_info[:uid])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_login
    redirect_to root_path unless current_user
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :require_login

  def index
    park_presenter = ParkPresenter.new(params)
    @current_location ||= park_presenter.current_location
    if @current_location[:lat].nil? || @current_location[:long].nil?
      flash[:failure] = 'You have entered an invalid address. Please re-enter a valid address.'
      redirect_to search_path
    else
      @parks = park_presenter.parks_search
    end
  end

  def show
    @park = Park.find(params[:id])
    @photos = FlickrPresenter.new(@park.latitude, @park.longitude).photos
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :require_login
  
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    if user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = user.id
      redirect_to search_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trippin</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Montserrat|Oswald' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class='navbar'>
      <a><%= image_tag 'l3.png', :class => "main-logo"%></a>
      <% if current_user  %>
        <section class="admin">
          <p class='user_name'>Welcome, <%= current_user.first_name %><p>
          <%= link_to 'Search', search_path, :class => 'navbar-text' %>
          <%= link_to 'Logout', logout_path, method: :delete, :class => 'navbar-text' %>
        </section>
      <% else %>
        <section class='admin'>
          <%= link_to 'Sign in with Google', google_login_path, :class => 'sign-in-text' %>
        </section>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/parks/_list.html.erb
<hr/ class='horizontal-line' >
<div class='park'>
  <% @parks.each do |park| %>
  <div class='park-row'>
    <p class=park_<%= park.id %>>
        <p class='park-name'><%= link_to "#{park.full_name}, #{park.state}", park_path(park) %></p><br>
        <p class ='park-description'><%= park.description %></p>
      <hr/>
    </p>
</div>
  <% end %>
</div>

app/views/parks/_map.html.erb
<div id="map"></div>
<script>
  function initMap() {
    // Add the current location
    var yourLocation = {
      position: {
        lat: <%= @current_location[:lat] %> ,
        lng: <%= @current_location[:long] %>
      },
      info: 'Your Location'};

    // Create an array of the found parks with their position and information for the info window
    var parks = []
    <% @parks.each do |park| %>
      parks.push({position: {lat: <%= park.latitude %>, lng: <%= park.longitude %>}, info: '<%= link_to park.full_name, park_path(park) %>'})
    <% end %>

    // Set the perspective of the map along with what location should the map be centered at
    var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 8, center: yourLocation.position});

    // Bounds: Add a LatLngBounds Object to expand the map so that all the markers fill the map
    var bounds = new google.maps.LatLngBounds();
    // Pin the market and create and info window for the current location
    var marker = new google.maps.Marker({
      position: yourLocation.position,
      map: map,
      icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
    });
    var infoWindow = new google.maps.InfoWindow({
      content: yourLocation.info
    });

    // Close infowindow: Save previously opened infowindow in a variable and then close when new one opens
    var currWindow =false;

    marker.addListener('mouseover', function() {
      // Put in conditional to see if currwindow (previously opened window) is open. If yes, then close
      if ( currWindow ) {
        currWindow.close();
      }
      // Assign previously opened infowindow to the currwindow variable
      currWindow = infoWindow;
      infoWindow.open(map, marker);
    });
    // Bounds: Extend the bounds to include the marker's location
    bounds.extend(yourLocation.position)

    // Pin the markers and the info windows for each of the found parks
    parks.forEach(park => {
      var marker = new google.maps.Marker({
        position: park.position,
        map: map
      });
      var infoWindow = new google.maps.InfoWindow({
        content: park.info
      });
      marker.addListener('mouseover', function() {
        if( currWindow ) {
          currWindow.close();
        }
        currWindow = infoWindow;
        infoWindow.open(map, marker);
      });
      // Bounds: Extend the bounds to include the marker's location
      bounds.extend(park.position)
    });
    // Bounds: Now update the maps to fit those bounds. This will adjust the zoom automatically
    map.fitBounds(bounds);
  }
</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?libraries=places&key=<%= ENV['GOOG_GEO_KEY'] %>&callback=initMap">
</script>

app/views/parks/index.html.erb
<%= stylesheet_link_tag 'searchpark', media: 'all' %>

<% if @parks.length == 0 %>
  <div id='parks-index-title'><h4><strong><span class='radius-word'>No</span></strong> National Parks found within <strong><span class='radius-word'><%= "#{params[:radius]}" %> miles</span></strong> of your current location. Please try again.</h4></div>
  <p class="previous-icon" title="Return to Previous Page"><%= link_to image_tag("goBack.png", height: 35, width: 125), search_path %></p>
<% else %>
  <div id='parks-index-title'><h4><strong><span class='radius-word'><%= @parks.length %></span></strong> National Parks found within <strong><span class='radius-word'><%= "#{params[:radius]}" %> miles</span></strong> of your current location </h4></div>
  <div id='parks-index-subtitle'><h4>Select a park from the map or list to continue...</h4></div>
  <div class='view-buttons'>
    <div class="w3-bar w3-black">
      <button class="w3-button" onclick="openView('map')">Map View</button>
      <button class="w3-button" onclick="openView('list')">List View</button>
    </div>
  </div>
<!-- Render View -->
  <div id="map" class="view">
    <%= render 'map' %>
  </div>
  <div id="list" class="view">
    <%= render 'list' %>
  </div>
<% end %>

<!-- Javascript -->
<script>
function openView(viewName) {
  var i;
  var x = document.getElementsByClassName("view");
  for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
  }
  document.getElementById(viewName).style.display = "block";
}
</script>

app/views/parks/show.html.erb
<%= stylesheet_link_tag 'searchpark', media: 'all' %>
<p class="previous-icon" title="Return to Previous Page"><%= link_to image_tag("goBack.png", height: 35, width: 125), :back %></p>
<div id='park-index-title'><h4><%= @park.full_name %>, <%= @park.state %></h4></div>
<div id='parks-index-subtitle'><h4>Position: <%= @park.latitude %>, <%= @park.longitude %></h4></div>
<div id='parks-description'><h4 class='desc-text'><%= @park.description %></h4></div>
<div class='park-hr'><hr/></div>
<section class="flickr_images">
  <% @photos.each do |photo| %>
    <article>
      <img class="flickr-images" src="<%= photo.url %>" alt="<%= photo.title %>"/>
    </article>
  <% end %>
</section>

app/views/search/_slideshow.html.erb
<!-- Slideshow -->
<div class="slideshow-container">
  <!-- Full-width images with number and caption text -->
  <div class="mySlides fade">
    <img src='<%= asset_path( 'us1.jpg' )%>' style="width:100%">
    <div class="text">Tunnel View, Yosemite National Park, California</div>
  </div>

  <div class="mySlides fade">
    <img src='<%= asset_path( 'us5.jpg' )%>' style="width:100%">
    <div class="text">Arches National Park, Utah</div>
  </div>

  <div class="mySlides fade">
    <img src='<%= asset_path( 'us2.jpg' )%>' style="width:100%">
    <div class="text">Half Dome, Yosemite National Park, California</div>
  </div>

  <div class="mySlides fade">
    <img src='<%= asset_path( 'us4.jpg' )%>' style="width:100%">
    <div class="text">Death Valley National Park, California</div>
  </div>

  <div class="mySlides fade">
    <img src='<%= asset_path( 'us3.jpg' )%>' style="width:100%">
    <div class="text">Yosemite National Park, California</div>
  </div>
</div>

<!-- JS for the slideshow -->
<script>
  var slideIndex = 0;
  showSlides();

  function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}
    slides[slideIndex-1].style.display = "block";
    setTimeout(showSlides, 6000); // Change image every 6 seconds
  }
</script>

app/views/search/index.html.erb
<%= stylesheet_link_tag 'searchpark', media: 'all' %>

<div class='search-page'>
  <% if current_user %>
  <div class='search-box'>
    <div id='search-title'><h2>Enter a Location To Find Nearby National Parks</h2></div>
    <%= form_tag :parks, method: :get, :class => 'form' do %>
      <%= text_field_tag 'street', nil, placeholder: 'Street', class: "input address", :required => true %>
      <%= text_field_tag 'city', nil, placeholder: 'City', class: "input address", :required => true %>
      <%= text_field_tag 'state', nil, placeholder: 'State', class: "input address", :required => true %>
      <%= text_field_tag 'radius', nil, placeholder: 'Radius (miles)', class: "input address", :required => true, type: 'number' %>
      <%= hidden_field_tag :tab, 'map' %>
      <button class="btn btn-primary" type="submit">Submit</button>
    <% end %>
  </div>
  <% end %>
</div>
<%= render 'slideshow' %>

app/views/welcome/index.html.erb
<div class="navigation">
  <div class="navigation-left">
    <a><%= image_tag 'l3.png', :class => "home-page-logo"%></a>
  </div>
  <div class="navigation-right">
    <button type="button" class="login-btn" name="button"><%= link_to 'Sign in with Google', google_login_path, :class => 'sign-in-text' %></button>
  </div>
</div>


<!-- Slider Wrapper -->
<div class="css-slider-wrapper">
  <input type="radio" name="slider" class="slide-radio1" checked id="slider_1">
  <input type="radio" name="slider" class="slide-radio2" id="slider_2">
  <input type="radio" name="slider" class="slide-radio3" id="slider_3">

  <!-- Slider Pagination -->
  <div class="slider-pagination">
    <label for="slider_1" class="page1"></label>
    <label for="slider_2" class="page2"></label>
    <label for="slider_3" class="page3"></label>
  </div>

  <!-- Slider #1 -->
  <div class="slider slide-1">
    <%= image_tag 'us4.jpg' %>
    <div class="slider-content">
      <h2>Find <span class="slider-word">National Parks</span> Near Your Location...</h2>
    </div>
  </div>

  <!-- Slider #2 -->
  <div class="slider slide-2">
    <%= image_tag 'us1.jpg' %>
    <div class="slider-content">
      <h2>Check Out <span class="slider-word">Photos</span> Of Your Chosen <span class="slider-word">Park</span>...</h2>
    </div>
  </div>

  <!-- Slider #3 -->
  <div class="slider slide-3">
    <%= image_tag 'us5.jpg' %>
    <div class="slider-content">
      <h2>Click on <span class="slider-word">'Sign in with Google'</span> To Begin This Journey</h2>
    </div>
  </div>

<script>
  var TIMEOUT = 6000;
  var interval = setInterval(handleNext, TIMEOUT);

  function handleNext() {

    var $radios = $('input[class*="slide-radio"]');
    var $activeRadio = $('input[class*="slide-radio"]:checked');
    var currentIndex = $activeRadio.index();
    var radiosLength = $radios.length;

    $radios
      .attr('checked', false);

    if (currentIndex >= radiosLength - 1) {
      $radios
        .first()
        .attr('checked', true);
    } else {
      $activeRadio
        .next('input[class*="slide-radio"]')
        .attr('checked', true);
    }
  }
</script>